#!/usr/bin/env bash
# install.sh — wire this repo into every AI coding harness found on the machine.
#   Claude Code, OMP, Gemini CLI  -> rules via @import (they expand it themselves)
#   Codex, OpenCode               -> rules rendered flat (they do not expand @imports)
#   any other harness             -> scripts/render-rules.sh <entry> > <its rules file>
# Idempotent. Anything replaced is moved to ~/.harness-backup/<stamp>/ first.
# Never edits settings.json, never touches sessions/auth, never deletes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y-%m-%d-%H%M%S)"
BACKUP="$HOME/.harness-backup/$STAMP"
CHANGED=0
GENERATED_MARK="<!-- GENERATED by harness/install.sh from"

tilde() { case "$1" in "$HOME"/*) printf '~/%s' "${1#"$HOME"/}";; *) printf '%s' "$1";; esac; }
say()   { printf '%s\n' "$*"; }
note()  { printf '  %s\n' "$*"; }

backup_then() {
  local dst="$1" rel; rel="${dst#"$HOME"/}"
  mkdir -p "$BACKUP/$(dirname "$rel")"; mv "$dst" "$BACKUP/$rel"
  note "backed up $dst -> $BACKUP/$rel"
}

link() {  # link <repo-path> <home-path>
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then return; fi
  if [ -e "$dst" ] || [ -L "$dst" ]; then backup_then "$dst"; fi
  ln -s "$src" "$dst"; note "linked $dst"; CHANGED=1
}

ensure_line() {  # ensure_line <file> <exact-line>
  local file="$1" line="$2"
  if [ -f "$file" ] && grep -qxF -- "$line" "$file"; then return; fi
  if [ -f "$file" ]; then mkdir -p "$BACKUP"; cp "$file" "$BACKUP/$(basename "$file").before"; fi
  mkdir -p "$(dirname "$file")"; printf '%s\n' "$line" >> "$file"
  note "added to $file: $line"; CHANGED=1
}

render_into() {  # render_into <target-file> <label>
  local dst="$1" label="$2" tmp
  tmp="$(mktemp)"
  { printf '%s %s. Do not edit; change %s or %s and re-run install.sh -->\n\n' \
      "$GENERATED_MARK" "$(tilde "$RULES")" "$(tilde "$HERE")" "$(tilde "$PRIVATE")"
    "$HERE/scripts/render-rules.sh" "$RULES"; } > "$tmp"
  if [ -f "$dst" ] && ! head -1 "$dst" | grep -qF "$GENERATED_MARK"; then
    note "$label: $dst exists and is hand-written; left alone. To adopt: scripts/render-rules.sh $(tilde "$RULES") > $(tilde "$dst")"
    rm -f "$tmp"; return
  fi
  if [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then rm -f "$tmp"; return; fi
  mkdir -p "$(dirname "$dst")"; mv "$tmp" "$dst"; note "$label: rendered $dst"; CHANGED=1
}

say "harness install from $HERE"

# 1. Rules entry file (the one with @imports). Claude Code reads ~/.claude/CLAUDE.md;
#    a pre-existing ~/CLAUDE.md is honored instead so the two never double-load.
RULES="$HOME/.claude/CLAUDE.md"; [ -f "$HOME/CLAUDE.md" ] && RULES="$HOME/CLAUDE.md"
PRIVATE="$HOME/CLAUDE.private.md"
ensure_line "$RULES" "@$(tilde "$HERE")/AGENTS.md"
ensure_line "$RULES" "@$(tilde "$PRIVATE")"
if [ ! -f "$PRIVATE" ]; then
  cat > "$PRIVATE" <<'EOF'
# Personal Rules (never committed)

Your preferences, project trigger rules, and tech-stack notes go here.
Opt-in modules: add one of these lines to the file that imports the harness
(the line must be exactly the @path, at column 1):
  @~/harness/modules/communication-contract.md
  @~/harness/modules/teach-mode.md
EOF
  note "created $PRIVATE"; CHANGED=1
fi

# 2. Claude Code: agents, hooks, statusline, skills.
for f in "$HERE"/claude/agents/*.md; do link "$f" "$HOME/.claude/agents/$(basename "$f")"; done
for f in "$HERE"/claude/hooks/*.sh;  do chmod +x "$f"; link "$f" "$HOME/.claude/hooks/$(basename "$f")"; done
link "$HERE/claude/statusline.sh" "$HOME/.claude/statusline.sh"
for d in "$HERE"/claude/skills/*/;   do d="${d%/}"; link "$d" "$HOME/.claude/skills/$(basename "$d")"; done
if [ ! -f "$HOME/.claude/settings.json" ]; then
  cp "$HERE/claude/settings.example.json" "$HOME/.claude/settings.json"; note "installed ~/.claude/settings.json"; CHANGED=1
else
  note "Claude Code: settings.json exists; copy the hooks/statusLine you want from claude/settings.example.json"
fi

# 3. OMP: imports (it reads ~/.claude/skills itself).
if [ -d "$HOME/.omp/agent" ]; then
  OMP="$HOME/.omp/agent/AGENTS.md"
  ensure_line "$OMP" "@$(tilde "$RULES")"
  ensure_line "$OMP" "@$(tilde "$HERE")/omp/AGENTS.md"
  [ -f "$HOME/.omp/agent/config.yml" ] || note "OMP: copy omp/config.example.yml to ~/.omp/agent/config.yml and set your models"
fi

# 4. Gemini CLI: imports.
if [ -d "$HOME/.gemini" ]; then
  ensure_line "$HOME/.gemini/GEMINI.md" "@$(tilde "$RULES")"
fi

# 5. Codex and OpenCode: no @imports, so the rules are rendered flat. Skills are linked for Codex.
if [ -d "$HOME/.codex" ]; then
  render_into "$HOME/.codex/AGENTS.md" "Codex"
  for d in "$HERE"/claude/skills/*/; do d="${d%/}"; link "$d" "$HOME/.codex/skills/$(basename "$d")"; done
fi
if [ -d "$HOME/.config/opencode" ]; then
  render_into "$HOME/.config/opencode/AGENTS.md" "OpenCode"
fi

# 6. Secret gate on every commit in this repo.
if git -C "$HERE" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git -C "$HERE" config core.hooksPath .githooks
fi

# 7. Tools the hooks expect.
for t in trash jq; do command -v "$t" >/dev/null 2>&1 || note "missing tool: $t (see README > Requirements)"; done

note "any other harness: $(tilde "$HERE")/scripts/render-rules.sh $(tilde "$RULES") > <its rules file>"
if [ "$CHANGED" = 1 ]; then say "done. start a new agent session to load the changes."; else say "already up to date."; fi
